[package]
name = "astraea-derive"
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }

[dependencies]
syn = "2.0"
quote = "1.0"

[lib]
proc-macro = true
