[package]
name = "libastraea"
version = "0.1.0"
edition = "2024"

[dependencies]
strum = { version = "0.27", features = ["derive"] }

[dev-dependencies]
rand = "0.9.2"
criterion = { version = "0.7.0", features = ["html_reports"] }

[[bench]]
name = "natural"
harness = false
