[book]
authors = ["Ivan Shelepugin <shelepuginivanm@gmail.com>"]
language = "en"
src = "src"
title = "astraea"

[output.html]
default-theme = "ayu"
mathjax-support = true
smart-punctuation = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
