[package]
name = "astraea-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "astraea"
path = "src/main.rs"
doc = false

[dependencies]
ariadne = "0.5.1"
astraea = { path = "../astraea" }
astraea-modules = { path = "../astraea-modules" }
clap = { version = "4.5.50", features = ["derive"] }
